development:
  adapter: postgresql
  encoding: unicode
  database: test_postgres_development
  pool: 5
  username: fails2deliver
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: test_postgres_test
  pool: 5
  username: fails2deliver
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: postgres_production
  pool: 5
  username: fails2deliver
  password: password